#!/usr/bin/perl
$file = @ARGV[0];
$n = @ARGV[1];
$m = @ARGV[2];
@d = `cat $file | head -n $m | tail -n +$n`;
$c = `dirname $file`;
chomp($c);
$fname = `basename $file`;
chomp($fname);
$cmd = "(cd $c ; git ls-files --full-name $fname)";
$path = `$cmd`;
$branch = `(cd $c; git branch --show-current)`;
chomp($branch);
$url = `(cd $c; git  remote get-url origin)`;
if (length($path)==0) {$path=$file}
chomp($path);
$i = $n;
%types = ('sol' => 'solidity', 'pl' => 'perl', 'htm' => 'html', 'py' => 'python');
%quotes = ('solidity' => '//', 'perl' => '#', 'javascript' => '//');
my($end) = $file =~ m/.*\.(\w{1,6})/;
$type = $types{$end};
if (length($type)==0){
    $fi = `file $file`;
    chomp($fi);
    my($t) =$fi=~ m/\s(\w*)\sscript/;
    $t  =~ tr/[A-Z]/[a-z]/ ;
    $type = $t;
}
$quote = $quotes{$type};
if (length($quote)==0){ $quote = '#';}
chomp($url);
my(@upath) = $url =~ m/^(https:\/\/|http:\/\/|git\@).*?[\/:](.*?\/.*?)(\.git)?$/;
if ($ENV{'BLOB'}){
print "[$path Line $n of $upath[1] ``$branch``](https://github.com/$upath[1]/blob/$branch/$path". "\#L" . $n . ")" ."\n";
}else{
my($chash) = `(cd $c; git log --pretty=oneline -n 1)` =~ m/^([a-z,0-9]+?) /;
print "[$path Line $n of $upath[1] ``$branch``](https://github.com/$upath[1]/tree/$chash/$path". "\#L" . $n . ")" ."\n";
}
print "```" . $type .  "\n";
if (not $ENV{'NOREF'}){
    print $quote . " File: $path\n";
    print $quote . " Lines: $n-$m\n\n";
}
$is = $m . ' ';
$sp = length($is) - 1;
for (@d){
    $io = $i . '                      ';
    $ip = substr($io,0,$sp);
    if ($ENV{'NONUM'}){
        print $_;
    }else{
        print $ip . ' ' . $_;
    }
    $i++;
}
print "```\n\n";
